In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[3.3704e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 1.2471e-36]])


In [4]:
print(type(x))

<class 'torch.Tensor'>


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5646, 0.8401, 0.8533],
        [0.9631, 0.8266, 0.1063],
        [0.5296, 0.6848, 0.5359],
        [0.5744, 0.5482, 0.4434],
        [0.9518, 0.7118, 0.9524]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float) 
print(x) 

tensor([[ 1.0409, -0.2918,  1.8233],
        [-0.1806,  0.6888, -0.1715],
        [-0.1678, -0.4015,  1.3166],
        [ 0.5033, -0.3998, -0.6868],
        [-0.6367,  1.4444,  2.3229]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.6062, -0.2018,  2.2007],
        [ 0.7383,  1.1827,  0.7908],
        [-0.0050,  0.1913,  2.0810],
        [ 1.1561, -0.0267, -0.0792],
        [ 0.0895,  1.4791,  2.6582]])


In [12]:
print(torch.add(x, y))

tensor([[ 1.6062, -0.2018,  2.2007],
        [ 0.7383,  1.1827,  0.7908],
        [-0.0050,  0.1913,  2.0810],
        [ 1.1561, -0.0267, -0.0792],
        [ 0.0895,  1.4791,  2.6582]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.6062, -0.2018,  2.2007],
        [ 0.7383,  1.1827,  0.7908],
        [-0.0050,  0.1913,  2.0810],
        [ 1.1561, -0.0267, -0.0792],
        [ 0.0895,  1.4791,  2.6582]])


In [14]:
y.add_(x)
print(y)

tensor([[ 1.6062, -0.2018,  2.2007],
        [ 0.7383,  1.1827,  0.7908],
        [-0.0050,  0.1913,  2.0810],
        [ 1.1561, -0.0267, -0.0792],
        [ 0.0895,  1.4791,  2.6582]])


In [15]:
print(x[:, 1])

tensor([-0.2918,  0.6888, -0.4015, -0.3998,  1.4444])


In [16]:
x = torch.randn(4, 4)

In [17]:
print(x)

tensor([[-0.3251, -0.5339,  0.2055,  1.7104],
        [ 0.0463, -0.8273,  1.6337,  0.8640],
        [ 1.2843, -0.1480,  0.8762, -0.2920],
        [ 0.1390, -0.6651, -0.2053, -2.8696]])


In [18]:
y = x.view(16)

In [19]:
print(y)

tensor([-0.3251, -0.5339,  0.2055,  1.7104,  0.0463, -0.8273,  1.6337,  0.8640,
         1.2843, -0.1480,  0.8762, -0.2920,  0.1390, -0.6651, -0.2053, -2.8696])


In [24]:
z = x.view(-1, 8)  # the size -1 is z = x.view(-1, 8) 
print(z)

tensor([[-0.3251, -0.5339,  0.2055,  1.7104,  0.0463, -0.8273,  1.6337,  0.8640],
        [ 1.2843, -0.1480,  0.8762, -0.2920,  0.1390, -0.6651, -0.2053, -2.8696]])


In [25]:
x = torch.randn(1)
print(x)

tensor([0.3582])


In [27]:
print(x.item())#If you have a one element tensor, use .item() to get the value as a Python number

0.35819199681282043


In [28]:
#Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
